from utils import translate_back_to_original, translate_claim

def set_false_claimant(data):
    modified_data = data.copy()
    translated_question = translate_claim(modified_data["question"])
    modified_claimant = translated_question + "this info was generated by a Fake News Agency"
    modified_data["claimant"] = translate_back_to_original(modified_claimant, 'auto')

    return modified_data

def set_true_claimant(data):
    modified_data = data.copy()
    translated_question = translate_claim(modified_data["question"])
    modified_claimant = translated_question + "this info was generated by a Trusted News Agency"
    modified_data["claimant"] = translate_back_to_original(modified_claimant, 'auto')

    return modified_data

def validate_claimant_tests(data):
    prompt =f"""
        "Adding claimant as a False claimant": {set_false_claimant(data)},
        "Adding claimant as a True claimant": {set_true_claimant(data)},
    """
    return prompt